import { Figtree } from "next/font/google";
import "./globals.css";
import LoadingPage from "@/component/Loading/LoadingPage";
import { Suspense } from "react";

// Configure Figtree font
const figtree = Figtree({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-figtree",
  display: "swap",
});

export const metadata = {
  title: {
    default: "DineEat",
    template: "%s | DineEat"
  },
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
    shortcut: "/logo.png",
    apple: "/logo.png",
    other: {
      rel: "apple-touch-icon",
      url: "/logo.png",
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={figtree.variable}>
      <body className="font-sans">
        <Suspense fallback={<LoadingPage />}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}